version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql_techblog
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=techblog
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - techblog_data:/var/lib/mysql

volumes:
  techblog_data: